config/routes.rb
Rails.application.routes.draw do
  get 'picture/index'
  get 'picture/bleach'
  get 'picture/onepiece'
  get 'picture/naruto'

  root 'picture#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
  def index
  end

  def bleach
  end

  def naruto
  end

  def onepiece
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Otaku</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/picture/bleach.html.erb
<h1>Bleach Characters</h1>

<h3>Ichigo</h3>
    <%= image_tag('ichigo.jpg', size: "400x200") %>
    <p>Ichigo Kurosaki  is a fictional character in the Bleach manga series
    and its adaptations created by Tite Kubo. The protagonist of the series,
    Ichigo receives Soul Reaper powers as a result of a run-in with Rukia Kuchiki,
    the Soul Reaper assigned to patrol his city, the fictional Karakura Town.
    These powers come at the cost of Rukia's own, and as a result, Ichigo
    concedes to work as Rukia's stand-in, fighting to protect people from
    evil spirits called Hollows and sending good spirits, wholes, to Soul Society.</p>

<h3>Chad</h3>
    <%= image_tag('chad.jpg', size: "400x200") %>
    <p>Yasutora Sado is a fictional character in the anime and manga series
    Bleach created by Tite Kubo. He is an extremely tall teenager who studies
    in the same class as Ichigo Kurosaki. When first introduced, Chad had no
    special powers aside from his unusual strength and endurance. After his
    encounter with the parakeet containing the soul of Yūichi Shibata, he
    starts to detect the approximate locations of spirits and hollows, but
    cannot fully see them. Only after saving Karin Kurosaki from a hollow,
    during the hollow-slaying match between Uryū and Ichigo, does Chad begin
    to fully see spirits. This also awakens what Chad later learns to be his
    latent powers as a Fullbringer, a human who manipulates the soul of an
    object to its full potential as the result of absorbing residual spirit
    pressure from a Hollow while unborn.</p>

<h3>Rukia</h3>
    <%= image_tag('rukia.jpg', size: "400x200") %>
    <p>Rukia Kuchiki is a fictional character in the anime and manga series
    Bleach created by Tite Kubo. In the series, Rukia Kuchiki is a Soul Reaper
    in charge of slaying evil spirits known as Hollows. At the beginning, after
    a brief meeting with the protagonist of the series, Ichigo Kurosaki, who can
    see supernatural beings such as Soul Reapers, she is forced to give him her
    powers in order to fulfill her duties as a Soul Reaper.</p>

<h3>Ishida</h3>
    <%= image_tag('ishida.jpg', size: "400x200") %>
    <p>Uryū Ishida is a fictional character and major figure in the anime
    and manga series Bleach created by Tite Kubo. Uryū is introduced in the
    series as a classmate of the Soul Reaper Ichigo Kurosaki, who reveals himself
    to be a Quincy, a clan of humans which was destroyed by the Soul Reapers.
    Wanting to prove the Quincies were better, Uryū challenges Ichigo to see who
    could kill more Hollows. However, once they are overpowered and start working
    together, they start getting to know each other, to the point they become friends.
    Since then, Uryū appears in the series as an ally to Ichigo, accompanying him in
    every fight he has.</p>

<h3>Orihime</h3>
    <%= image_tag('orihime.jpg', size: "400x200") %>
    <p>Orihime Inoue is a fictional character in the Bleach manga series and its
    adaptations created by Tite Kubo. She is a classmate and friend of Ichigo
    Kurosaki, the main character of the series. Like many other friends of Ichigo,
    she quickly develops spiritual powers of her own after Ichigo becomes a Soul
    Reaper. Through the series, Orihime learns about Ichigo's duties as a Soul
    Reaper and decides to accompany him when he goes to Soul Society to save Rukia Kuchiki.</p>

app/views/picture/index.html.erb
<h1>OTAKUTown</h1>

  <h3><%= link_to "One Piece", picture_onepiece_path %></h3>
  <%= link_to image_tag("onepiece.jpg", size: '260x180'), picture_onepiece_path %>

  <h3><%= link_to "Bleach", picture_bleach_path %></h3>
  <%= link_to image_tag("bleach.jpg", size: '260x180'), picture_bleach_path%>

  <h3><%= link_to "Naruto Shippuden", picture_naruto_path %></h3>
  <%= link_to image_tag("naruto.jpg", size: '260x180'), picture_naruto_path %>

app/views/picture/naruto.html.erb
<h1>Naruto Shippuden Characters</h1>

<h3>Naruto</h3>
    <p>Naruto Uzumaki is a shinobi of Konohagakure. He became the jinchūriki
    of the Nine-Tails on the day of his birth — a fate that caused him to
    be ostracised by most of Konoha throughout his childhood. After joining
    Team Kakashi, Naruto worked hard to gain the village's acknowledgement
    all the while chasing his dream to become Hokage.</p>

<h3>Sakura</h3>
    <p>Sakura Uchiha is a kunoichi of Konohagakure. When she is assigned to
    Team 7, Sakura quickly finds herself ill-prepared for the duties of a ninja
    and the complications of her team-mates' lives. By training under her master,
    Tsunade, she becomes a strong kunoichi and an excellent medical-nin, capable
    of facing the challenges of life as a ninja, as well as helping her friends
    and loved ones when they need her. </p>

<h3>Sasuke</h3>
    <p>Sasuke Uchiha is one of the last surviving members of Konohagakure's
    Uchiha clan. After his older brother, Itachi, slaughtered their clan, Sasuke
    made it his mission in life to avenge them. He is added to Team 7 upon becoming
    a ninja and, through competition with his rival and best friend, Naruto Uzumaki,
    Sasuke starts developing his skills. Dissatisfied with his progress, causing him
    to defect from Konoha so that he can acquire the strength needed to have his revenge.</p>

app/views/picture/onepiece.html.erb
<h1>One Piece Characters</h1>

<h3>Luffy</h3>
    <%= image_tag('luffy.jpg', size: '400x200') %>
    <p>Monkey D. Luffy is the primary protagonist of the One Piece series.
    At the age of seven, he admires and tries to join the pirates of the
    "Red Haired" Shanks. Ridiculed and rejected, he inadvertently eats their
    treasure, the Paramecia-type Gum-Gum Fruit, which gives his body the
    properties of rubber. His reckless efforts ultimately lead him into grave
    peril and cause Shanks to lose an arm while rescuing him. After that,
    Luffy gives up on joining Shanks. Instead he resolves to start a crew of
    his own and become King of the Pirates.</p>

<h3>Zoro</h3>
    <%= image_tag('zoro.jpg', size: '400x200') %>
    <p>Roronoa Zoro is a swordsman who uses up to three swords simultaneously,
    holding one in each hand and a third in his mouth. To fulfill a promise to
    Kuina, his deceased childhood rival, he aims to replace "Hawk Eyes" Mihawk
    as the world's greatest swordsman.</p>

<h3>Nami</h3>
    <%= image_tag('nami.jpg', size: '400x200') %>
    <p>Adopted and raised by Navy seaman turned tangerine farmer Bellemere,
    Nami and her older sister Nojiko , have to witness their mother
    being murdered by the infamous Arlong, whose pirate gang occupies their
    island and extracts tribute from the population. Striking a deal with him,
    Nami, still a child but already an accomplished cartographer who dreams of
    drawing a complete map of the world, joins the pirates, hoping to eventually
    buy freedom for her village. Growing up as a pirate-hating pirate, drawing
    maps for Arlong and stealing treasure from other pirates, Nami becomes an
    excellent burglar, pickpocket and navigator with an exceptional ability to
    forecast weather. After Arlong betrays her, and he and his
    gang are defeated by the Straw Hat Pirates, Nami joins the latter in pursuit
    of her dream and acquires infamy herself as "Cat Burglar" Nami </p>

<h3>Brook</h3>
    <%= image_tag('brook.jpg', size: '400x200') %>
    <p>Already a pirate before the time of Roger, "Humming" Brook
     first enters the Grand Line as vice-captain
    of the music-themed Rumbar Pirates. Leaving their pet, the infant
    whale Laboon, behind at Reverse Mountain, they promise to return after
    sailing around the world. Instead, they are annihilated, with
    one exception. The power of the Paramecia-type Revive-Revive Fruit allows
    "Dead Bones" Brook to rise again and live a second life as a skeleton.
    Fifty years later, Brook's goal is still to fulfill his late crew's promise
    and to that end joins the Straw Hat Pirates.</p>

<h3>Franky</h3>
    <%= image_tag('franky.jpg', size: '400x200') %>
    <p>The son of pirate parents who abandon him at age ten, Cutty Flam ,
    nicknamed Franky, is taken in as an apprentice by a
    shipwright who secretly holds the plans for a devastating ancient weapon.
    Franky's recklessness eventually provides an opportunity to World Government
    agents seeking these plans.Attempting to rescue his master, Franky
    suffers severe injuries and only survives by rebuilding parts of his body using
    pieces of scrap metal, turning himself into a cola-powered cyborg with super-human
    strength. After gaining notoriety as "Cyborg" Franky
    and to fulfill his dream of sailing a ship he built around the world, he constructs
    the Thousand Sunny, a brigantine-rigged sloop-of-war, for the Straw Hat Pirates and joins the crew.</p>

<h3>Sanji</h3>
    <%= image_tag('sanji.jpg', size: '400x200') %>
    <p>While serving as an apprentice cook on a passenger ship, nine-year-old
    Sanji stands up to a boarding party of pirates led by the infamous "Red Foot"
    Zeff. During the encounter, Sanji is swept into
    the sea by a massive wave, but Zeff jumps after him because of their common
    dream of finding the All Blue, a legendary sea,
    containing every kind of fish in the world.</p>

<h3>Chopper</h3>
    <%= image_tag('chopper.jpg', size: '400x200') %>
    <p>Tony Tony "Cotton Candy Lover" Chopper is a doctor and a blue-nosed reindeer.
    The power of the Zoan-type Human-Human Fruit provides him with the ability
    to transform into a reindeer or a reindeer hybrid. A self-developed drug he
    calls Rumble Ball enables Chopper to perform
    even more transformations.</p>

<h3>Robin</h3>
    <p>Growing up in Ohara, home of the world's oldest and largest library,
    Nico Robin becomes an archaeologist at the age of eight. At some point
    she gains the power of the Paramecia-type Flower-Flower Fruit, which allows
    her to have temporary copies of parts of her body, including her eyes and
    ears, spring up on surfaces near her. Behind the backs of her teachers,
    she acquires from them the outlawed knowledge of how to translate the
    ancient stones called Poneglyph, which are scattered around the world,
    and comes to share their goal of finding the illusive Rio Poneglyph, which
    is said to tell the world's lost history.</p>

<h3>Usopp</h3>
    <p>During his early childhood, Usopp is abandoned by his father, Yasopp,
    who leaves to join the Red-Haired Pirates. Then, as Banchina, his mother,
    falls ill, Usopp starts telling tall tales, expressing his hope that his
    father would return and take them out to sea. Even after his mother dies,
    Usopp does not blame his father for leaving, but strives to become a great
    pirate himself, despite his cowardly disposition.</p>